name: Chrome
on:
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npx cypress run --browser chrome
  chrome-debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npx cypress run --browser chrome
        env:
            DEBUG: 'cypress:*,xvfb'
