name: Chrome ELECTRON_RUN_AS_NODE
on:
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npx cypress run --browser chrome
        env:
          ELECTRON_RUN_AS_NODE: 1

  chrome-verify:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Verify first
        run: npx cypress verify
      - name: Cypress run
        run: npx cypress run --browser chrome
        env:
          ELECTRON_RUN_AS_NODE: 1

  chrome-debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npx cypress run --browser chrome
        env:
            DEBUG: 'cypress:*,xvfb'
            ELECTRON_RUN_AS_NODE: 1

  chrome-verify-debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Verify first
        run: npx cypress verify
      - name: Cypress run
        run: npx cypress run --browser chrome
        env:
            DEBUG: 'cypress:*,xvfb'
            ELECTRON_RUN_AS_NODE: 1
