name: Electron
on:
  workflow_dispatch:

jobs:
  electron:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npx cypress run
  electron-debug:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npx cypress run
        env:
            DEBUG: 'cypress:*,xvfb'
